In [13]:
import numpy as np
import random 

In [14]:
movie_id=np.arange(1301,2301)
print(movie_id[:10])
movie_id.size

[1301 1302 1303 1304 1305 1306 1307 1308 1309 1310]


1000

In [22]:
user_id=[]
for i in range(20201,20301):
    user_id.append(i)
user_id=np.array(user_id)

In [24]:
user_id.size

100

In [25]:
user_id

array([20201, 20202, 20203, 20204, 20205, 20206, 20207, 20208, 20209,
       20210, 20211, 20212, 20213, 20214, 20215, 20216, 20217, 20218,
       20219, 20220, 20221, 20222, 20223, 20224, 20225, 20226, 20227,
       20228, 20229, 20230, 20231, 20232, 20233, 20234, 20235, 20236,
       20237, 20238, 20239, 20240, 20241, 20242, 20243, 20244, 20245,
       20246, 20247, 20248, 20249, 20250, 20251, 20252, 20253, 20254,
       20255, 20256, 20257, 20258, 20259, 20260, 20261, 20262, 20263,
       20264, 20265, 20266, 20267, 20268, 20269, 20270, 20271, 20272,
       20273, 20274, 20275, 20276, 20277, 20278, 20279, 20280, 20281,
       20282, 20283, 20284, 20285, 20286, 20287, 20288, 20289, 20290,
       20291, 20292, 20293, 20294, 20295, 20296, 20297, 20298, 20299,
       20300])

In [27]:
#creating a Single - Dimensional Array
arr=np.array([2,3,7])
print(arr)

[2 3 7]


In [29]:
#Creating a Mult-dimensional Array
arr=np.array([[10,20,30,],[40,50,60,]])
print(arr)
print(type(arr))

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>


In [30]:
# Using np.full()
X=np.full((2,3),5)
X

array([[5, 5, 5],
       [5, 5, 5]])

In [33]:
#Using np.linspace()
arr=np.linspace(0,20,5)#Returns a Linearly-Spaced Vector spacing
print(arr)

[ 0.  5. 10. 15. 20.]


#### Task 2: Create a matrix movies_matrix, to store users rating such that

In [34]:
import random

In [39]:
import random
movie_matrix = []
for user in range(100):
    movies_rated_by_me = np.full(1000,-1)
    num_movies_rated = random.randint(0,999)
    #random.seed(num_movies_rated)
    movies_that_i_will_rate = random.sample(range(0,1000),num_movies_rated)
    #user rating for movies they chosed to rate
    for index in movies_that_i_will_rate:
        movies_rated_by_me[index] = random.randint(0,10)
        movie_matrix.append(movies_rated_by_me)



In [38]:
movie_matrix=[]
for user in range(100):
    movie_rated_by_me=np.full(1000,-1)
    num_moive_rated=random.randint(0,999)
    #random.seed(nim_movie_rated)
    movie_that_i_will_rate=random.sample(range(0,1000),num_movies_rated)
    #user rating for movies they chosed to rate 
    for index in movies_that_i_will_rate:
        movies_rated_by_me[index]=random.randint(0,10)
        movie_matrix.append(movies_rated_by_me)

NameError: name 'num_movies_rated' is not defined