In [1]:
import numpy as np


In [2]:
np.__version__

'1.24.3'

In [3]:
arr=np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
arr.shape

(3,)

In [5]:
arr.size

3

In [6]:
arr.dtype

dtype('int32')

In [8]:
arr2=np.zeros([2,2])
print(arr2)

[[0. 0.]
 [0. 0.]]


In [9]:
arr2=np.ones(([3,3]))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
va=np.linspace(1,20,5)
print(va)

[ 1.    5.75 10.5  15.25 20.  ]


In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#creating a ndarray
x=[[0,1,2],[3,4,5],[6,7,8]]
a=np.array(x)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
a.shape

(3, 3)

In [25]:
a.ndim

2

In [26]:
a.size

9

In [28]:
a.dtype

dtype('int32')

In [30]:
a.itemsize

4

In [32]:
a=np.zeros([2,2])
print(a)

[[0. 0.]
 [0. 0.]]


In [33]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [36]:
a=np.array([1,2,3])
c=a.copy()
print(c)
a[0]=0
print(c)

[1 2 3]
[1 2 3]


In [37]:
#arange()
a=np.arange(0,20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [41]:
#linspace
import numpy as np
a=np.linspace(0,20,2)
print(a)

[ 0. 20.]
