In [1]:
import numpy as np

In [12]:
import numpy as np
a = np.arange(20)
print("Original Array:")
print(a)
b = a.reshape((5,4))
print("Reshaped Array:")
print(b)
c = a.transpose()
print("Transpose of Array:")
print(b)

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Transpose of Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [14]:
print("First array is: ")
a=np.array([[1,2],[3,4]])
print(a)
print("Second array is :")
b=np.array([[6,7],[8,9]])
print(b)
print("Appling hstack() function :")
c=np.hstack((a,b))
print(c)
print("Appling vstack() function :")
d=np.vstack((a,b))
print(d)
print("Appling concatenate() function :")
e=np.concatenate((a,b))
print(e)
print("Appling split() function :")
f=np.split(c,2)
print(f)

First array is: 
[[1 2]
 [3 4]]
Second array is :
[[6 7]
 [8 9]]
Appling hstack() function :
[[1 2 6 7]
 [3 4 8 9]]
Appling vstack() function :
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
Appling concatenate() function :
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
Appling split() function :
[array([[1, 2, 6, 7]]), array([[3, 4, 8, 9]])]


In [22]:
a=np.array([(1,2,3),(1,4,3)])
b=np.array([(2,3,4),(4,4,2)])
h=np.hstack((a,b))
h

array([[1, 2, 3, 2, 3, 4],
       [1, 4, 3, 4, 4, 2]])

In [21]:
a=np.array([(1,2,3),(1,4,3)])
b=np.array([(2,3,4),(4,4,2)])
np.vstack((a,b))

array([[1, 2, 3],
       [1, 4, 3],
       [2, 3, 4],
       [4, 4, 2]])

In [25]:
np.split(h,2)

[array([[1, 2, 3, 2, 3, 4]]), array([[1, 4, 3, 4, 4, 2]])]

In [28]:
a1=np.arange(16).reshape(4,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
np.hsplit(a1,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]