In [ ]:
 #Using Numpy
"""Once you've installed Numpy you can import it as a library"""

In [168]:
import numpy as np

In [ ]:
# Creating Numpy arrays from a python list

In [169]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [170]:
np.array(my_list)

array([1, 2, 3])

In [174]:
my_matrix=[[1,2,3],
           [4,5,6],
           [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [175]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [176]:
#built-in Methods

In [ ]:
# arange
"""Return evently spaced values within a given interval"""

In [177]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [182]:
# zeros and ones
np.ones(2)

array([1., 1.])

In [191]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [192]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [193]:
#linspace
"""Return evenly spaced numbers over a specified interval"""

In [194]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [195]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [ ]:
#eye 
""" Creates an identiy matrix"""

In [196]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#rand
'''Create an array of the given shape and populate it with 
random samples from a uniform distribution over[0,1]'''

In [197]:
np.random.rand(2)


array([0.76430574, 0.09713726])

In [198]:
np.random.rand(5,5)

array([[0.7078782 , 0.11881012, 0.76061633, 0.3688492 , 0.75822066],
       [0.8687179 , 0.5232482 , 0.95755053, 0.17090482, 0.66287462],
       [0.53983533, 0.31130708, 0.42456122, 0.56909472, 0.42043331],
       [0.37278722, 0.13768873, 0.70755386, 0.74284302, 0.23392852],
       [0.65334453, 0.85069353, 0.25634554, 0.52430018, 0.5239543 ]])

In [ ]:
#randn 
"""Return a sample (or samples) from the 'standard normal' 
distribution unlike rand which is uniform"""

In [199]:
np.random.randn(3)

array([1.04067016, 0.93798014, 0.88517183])

In [200]:
np.random.randn(5,5)

array([[-0.60350574,  1.05355416,  0.84073174,  0.88437376,  0.10566369],
       [-0.20193286, -0.60428215,  0.38639005,  3.25066727, -1.0459162 ],
       [ 0.02275622, -0.91440711, -0.93261765,  0.17870734, -1.1390588 ],
       [-0.42248161,  0.33021573,  0.44092831, -0.53427716, -0.72598577],
       [ 0.06079444,  1.90327862, -1.85644268,  1.0906733 ,  1.45198056]])

In [ ]:
#randint
"""Return random integers from low(inclusive)
to high (exclusive)"""

In [202]:
np.random.randint(1,100)

50

In [203]:
np.random.randint(1,100,15)

array([79, 15, 43, 79, 38, 89, 32, 50, 62, 15, 90, 18, 63, 14, 48])

In [ ]:
# Array Attributes and Methods
"""Lets's discuss some useful attributes and methods or an array"""

In [204]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [205]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [206]:
ranarr

array([ 2, 17, 43, 23, 48, 23, 39,  6,  5, 46])

In [207]:
arr.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [208]:
ranarr

array([ 2, 17, 43, 23, 48, 23, 39,  6,  5, 46])

In [209]:
ranarr.max()

48

In [210]:
ranarr.min()

2

In [211]:
ranarr.argmax()

4

In [212]:
ranarr.argmin()

0

In [213]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [216]:
y=arr.reshape(5,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [217]:
y.max()

24

In [218]:
y.min()

0

In [219]:
y.argmin()

0

In [220]:
y.argmax()

24

In [221]:
arr.shape

(25,)

In [222]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [226]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [227]:
#dtype
arr.dtype

dtype('int32')